use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Generate the mac_vendor_data.rs data file from the merged vendor map.
/// Writes a bare Rust array literal that gets pulled in via `include!()`.
pub fn generate_mac_vendors_rs(
    vendors: &BTreeMap<String, String>,
    output_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut lines = Vec::with_capacity(vendors.len() + 5);

    lines.push(format!(
        "// Auto-generated by oui-generator — {} entries. Do not edit.",
        vendors.len()
    ));
    lines.push("&[".to_string());

    for (prefix, vendor) in vendors {
        let escaped = vendor.replace('\\', "\\\\").replace('"', "\\\"");
        lines.push(format!("    (\"{}\", \"{}\"),", prefix, escaped));
    }

    lines.push("]".to_string());
    lines.push(String::new());

    fs::write(output_path, lines.join("\n"))?;

    eprintln!(
        "Generated {} with {} entries",
        output_path.display(),
        vendors.len()
    );
    Ok(())
}
