use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Generate the mac_vendors.rs source file from the merged vendor map.
pub fn generate_mac_vendors_rs(
    vendors: &BTreeMap<String, String>,
    output_path: &Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut lines = Vec::with_capacity(vendors.len() + 10);

    lines.push("//! MAC OUI vendor database. Maps thousands of MAC address prefixes (first 3 bytes)".to_string());
    lines.push("//! to their manufacturer names for device identification and classification.".to_string());
    lines.push(format!("//! Auto-generated by oui-generator with {} entries.", vendors.len()));
    lines.push(String::new());
    lines.push("// MAC OUI prefixes mapped to vendor names (first 3 bytes, lowercase, colon-separated)".to_string());
    lines.push("// Sorted lexicographically by prefix for binary search lookup".to_string());
    lines.push("pub(crate) const MAC_VENDOR_MAP: &[(&str, &str)] = &[".to_string());

    for (prefix, vendor) in vendors {
        // Escape any quotes in vendor name (shouldn't happen, but be safe)
        let escaped = vendor.replace('\\', "\\\\").replace('"', "\\\"");
        lines.push(format!("    (\"{}\", \"{}\"),", prefix, escaped));
    }

    lines.push("];".to_string());
    lines.push(String::new());

    fs::write(output_path, lines.join("\n"))?;

    eprintln!("Generated {} with {} entries", output_path.display(), vendors.len());
    Ok(())
}
